const allArtPieces = [
  {
    id: 1,
    src: "/src/assets/sketches/BHXP3462.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "03/12/2020",
    title: "",
    description: "Opera che sfida la percezione.",
    songName: "Melodia Infinita",
  },
  {
    id: 2,
    src: "/src/assets/sketches/BNQX3333.JPG",
    artist: ["rose-villain"],
    italianSong: false,
    date: "07/25/2021",
    title: "",
    description: "Visione onirica.",
    songName: "Ritmo Urbano",
  },
  {
    id: 3,
    src: "/src/assets/sketches/BPZD1936.JPG",
    artist: ["other", "tha-supreme"],
    italianSong: false,
    date: "11/03/2020",
    title: "",
    description: "Riflesso del subconscio.",
    songName: "Onda Sonora",
  },
  {
    id: 4,
    src: "/src/assets/sketches/CITE1837.JPG",
    artist: ["rose-villain", "other"],
    italianSong: false,
    date: "02/17/2022",
    title: "",
    description: "Esplorazione dell'infinito.",
    songName: "Eco di Vita",
  },
  {
    id: 5,
    src: "/src/assets/sketches/CJLC3545.JPG",
    artist: ["tha-supreme", "rose-villain"],
    italianSong: false,
    date: "09/06/2020",
    title: "",
    description: "Danza di colori.",
    songName: "Sogno Elettrico",
  },
  {
    id: 6,
    src: "/src/assets/sketches/CRFC1818.JPG",
    artist: ["other"],
    italianSong: false,
    date: "04/28/2021",
    title: "",
    description: "Armonia inaspettata.",
    songName: "Battito Nascosto",
  },
  {
    id: 7,
    src: "/src/assets/sketches/DOUI6761.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "01/15/2023",
    title: "",
    description: "Racconto silenzioso.",
    songName: "Risveglio",
  },
  {
    id: 8,
    src: "/src/assets/sketches/DSNX9207.JPG",
    artist: ["rose-villain"],
    italianSong: false,
    date: "05/09/2020",
    title: "",
    description: "Intensità emotiva.",
    songName: "Sfumature",
  },
  {
    id: 9,
    src: "/src/assets/sketches/EQYP1424.JPG",
    artist: ["other"],
    italianSong: false,
    date: "08/22/2021",
    title: "",
    description: "Sogno urbano.",
    songName: "Notte Stellata",
  },
  {
    id: 10,
    src: "/src/assets/sketches/ERQO3358.JPG",
    artist: ["tha-supreme", "other"],
    italianSong: false,
    date: "12/30/2020",
    title: "",
    description: "Ritratto del tempo.",
    songName: "Aria di Libertà",
  },
  {
    id: 11,
    src: "/src/assets/sketches/FBFH4847.JPG",
    artist: ["rose-villain"],
    italianSong: false,
    date: "03/07/2022",
    title: "",
    description: "Viaggio interstellare.",
    songName: "Vibrazione",
  },
  {
    id: 12,
    src: "/src/assets/sketches/FKNS0648.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "07/14/2021",
    title: "",
    description: "Melodia visiva.",
    songName: "Odissea",
  },
  {
    id: 13,
    src: "/src/assets/sketches/FKVK5005.JPG",
    artist: ["other", "rose-villain"],
    italianSong: false,
    date: "10/29/2020",
    title: "",
    description: "Incanto geometrico.",
    songName: "Sussurro",
  },
  {
    id: 14,
    src: "/src/assets/sketches/FXLR0871.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "06/11/2021",
    title: "",
    description: "Riflesso d'acqua.",
    songName: "Aura",
  },
  {
    id: 15,
    src: "/src/assets/sketches/GNQY6124.JPG",
    artist: ["other"],
    italianSong: false,
    date: "05/05/2022",
    title: "",
    description: "Trama della realtà.",
    songName: "Fuga",
  },
  {
    id: 16,
    src: "/src/assets/sketches/HCAN0173.JPG",
    artist: ["tha-supreme", "rose-villain"],
    italianSong: false,
    date: "08/18/2023",
    title: "",
    description: "Sospensione creativa.",
    songName: "Incanto",
  },
  {
    id: 17,
    src: "/src/assets/sketches/HOOW6277.JPG",
    artist: ["rose-villain", "other"],
    italianSong: false,
    date: "01/23/2020",
    title: "",
    description: "Fusione di mondi.",
    songName: "Riflessione",
  },
  {
    id: 18,
    src: "/src/assets/sketches/IAHA1176.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "04/10/2021",
    title: "",
    description: "Poesia in movimento.",
    songName: "Euforia",
  },
  {
    id: 19,
    src: "/src/assets/sketches/IGCS9328.JPG",
    artist: ["rose-villain"],
    italianSong: false,
    date: "09/19/2022",
    title: "",
    description: "Verità astratta.",
    songName: "Navigazione",
  },
  {
    id: 20,
    src: "/src/assets/sketches/IINJ0685.JPG",
    artist: ["other"],
    italianSong: false,
    date: "11/27/2020",
    title: "",
    description: "Eco di sensazioni.",
    songName: "Semplicità",
  },
  {
    id: 21,
    src: "/src/assets/sketches/KHAJ9471.JPG",
    artist: ["tha-supreme", "other"],
    italianSong: false,
    date: "02/04/2023",
    title: "",
    description: "Risonanza interiore.",
    songName: "Viaggio",
  },
  {
    id: 22,
    src: "/src/assets/sketches/Kid Yugi and featurings of I Diavoli Del Male album.png",
    artist: ["rose-villain"],
    italianSong: false,
    date: "08/08/2020",
    title: "",
    description: "Armonia dei contrasti.",
    songName: "Specchio",
  },
  {
    id: 23,
    src: "/src/assets/sketches/LTWV1703.JPG",
    artist: ["other", "tha-supreme"],
    italianSong: false,
    date: "12/16/2021",
    title: "",
    description: "Vibrazione contemporanea.",
    songName: "Armonia",
  },
  {
    id: 24,
    src: "/src/assets/sketches/MOPN1114.JPG",
    artist: ["rose-villain", "other"],
    italianSong: false,
    date: "07/21/2023",
    title: "",
    description: "Sinfonia di forme.",
    songName: "Contrasti",
  },
  {
    id: 25,
    src: "/src/assets/sketches/NEJC5049.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "03/31/2020",
    title: "",
    description: "Spirito ribelle.",
    songName: "Impronta",
  },
  {
    id: 26,
    src: "/src/assets/sketches/NIKE8692.JPG",
    artist: ["other"],
    italianSong: false,
    date: "09/13/2021",
    title: "",
    description: "Dimensione alternativa.",
    songName: "Fenomeno",
  },
  {
    id: 27,
    src: "/src/assets/sketches/NIOA5886.JPG",
    artist: ["tha-supreme", "rose-villain"],
    italianSong: false,
    date: "10/24/2022",
    title: "",
    description: "Mistero avvolgente.",
    songName: "Intreccio",
  },
  {
    id: 28,
    src: "/src/assets/sketches/OCHB6729.JPG",
    artist: ["rose-villain"],
    italianSong: false,
    date: "06/02/2020",
    title: "",
    description: "Magia del quotidiano.",
    songName: "Magia",
  },
  {
    id: 29,
    src: "/src/assets/sketches/OQMQ0348.JPG",
    artist: ["other"],
    italianSong: false,
    date: "04/26/2021",
    title: "",
    description: "Essenza del sogno.",
    songName: "Ombre",
  },
  {
    id: 30,
    src: "/src/assets/sketches/OQUS1839.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "11/12/2022",
    title: "",
    description: "Ritmo urbano.",
    songName: "Rinascita",
  },
  {
    id: 31,
    src: "/src/assets/sketches/PIKA5237.JPG",
    artist: ["rose-villain", "other"],
    italianSong: false,
    date: "05/05/2021",
    title: "",
    description: "Onda di emozioni.",
    songName: "Essenza",
  },
  {
    id: 32,
    src: "/src/assets/sketches/PIRC3235.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "09/09/2020",
    title: "",
    description: "Tramonto urbano.",
    songName: "Ambizione",
  },
  {
    id: 33,
    src: "/src/assets/sketches/PVIR4809.JPG",
    artist: ["other"],
    italianSong: false,
    date: "12/20/2021",
    title: "",
    description: "Vento creativo.",
    songName: "Aura di Sera",
  },
  {
    id: 34,
    src: "/src/assets/sketches/QDIW5520.JPG",
    artist: ["rose-villain", "tha-supreme"],
    italianSong: false,
    date: "08/02/2022",
    title: "",
    description: "Tempesta.",
    songName: "Tempesta",
  },
  {
    id: 35,
    src: "/src/assets/sketches/QFVH1418.JPG",
    artist: ["other"],
    italianSong: false,
    date: "03/15/2023",
    title: "",
    description: "Equilibrio.",
    songName: "Equilibrio",
  },
  {
    id: 36,
    src: "/src/assets/sketches/QUTJ4744.JPG",
    artist: ["tha-supreme", "rose-villain"],
    italianSong: false,
    date: "07/27/2020",
    title: "",
    description: "Fusione.",
    songName: "Fusione",
  },
  {
    id: 37,
    src: "/src/assets/sketches/QWFJ0522.JPG",
    artist: ["rose-villain"],
    italianSong: false,
    date: "02/08/2022",
    title: "",
    description: "Luce.",
    songName: "Luce",
  },
  {
    id: 38,
    src: "/src/assets/sketches/RGFU5150.JPG",
    artist: ["other", "tha-supreme"],
    italianSong: false,
    date: "06/19/2021",
    title: "",
    description: "Impronta del tempo.",
    songName: "Vento",
  },
  {
    id: 39,
    src: "/src/assets/sketches/RVRD7544.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "10/31/2020",
    title: "",
    description: "Forma in evoluzione.",
    songName: "Ritornello",
  },
  {
    id: 40,
    src: "/src/assets/sketches/SBBS9788.JPG",
    artist: ["rose-villain"],
    italianSong: false,
    date: "04/04/2022",
    title: "",
    description: "Spirale dell'arte.",
    songName: "Beat",
  },
  {
    id: 41,
    src: "/src/assets/sketches/SOJJ0828.JPG",
    artist: ["other"],
    italianSong: false,
    date: "01/16/2023",
    title: "",
    description: "Mistero del silenzio.",
    songName: "Sogno",
  },
  {
    id: 42,
    src: "/src/assets/sketches/SVIG8580.JPG",
    artist: ["tha-supreme", "rose-villain"],
    italianSong: false,
    date: "03/28/2021",
    title: "",
    description: "Festa della luce.",
    songName: "Inno",
  },
  {
    id: 43,
    src: "/src/assets/sketches/tha-supreme-sulla-luna.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "09/07/2020",
    title: "",
    description: "Eclettismo vibrante.",
    songName: "Vibrazioni",
  },
  {
    id: 44,
    src: "/src/assets/sketches/TWDW9166.JPG",
    artist: ["rose-villain", "other"],
    italianSong: false,
    date: "11/14/2022",
    title: "",
    description: "Ritmo vibrante.",
    songName: "Eclissi",
  },
  {
    id: 45,
    src: "/src/assets/sketches/UJXX4601.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "05/23/2021",
    title: "",
    description: "Universo in miniatura.",
    songName: "Onda",
  },
  {
    id: 46,
    src: "/src/assets/sketches/VCFR6377.JPG",
    artist: ["other"],
    italianSong: false,
    date: "07/30/2023",
    title: "",
    description: "Sguardo senza tempo.",
    songName: "Danze",
  },
  {
    id: 47,
    src: "/src/assets/sketches/VYEO1257.JPG",
    artist: ["tha-supreme", "rose-villain"],
    italianSong: false,
    date: "02/11/2022",
    title: "",
    description: "Battito creativo.",
    songName: "Riflessioni",
  },
  {
    id: 48,
    src: "/src/assets/sketches/WAKW3698.JPG",
    artist: ["other"],
    italianSong: false,
    date: "06/17/2021",
    title: "",
    description: "Sogno in fermento.",
    songName: "Miraggio",
  },
  {
    id: 49,
    src: "/src/assets/sketches/WCTL0854.JPG",
    artist: ["tha-supreme"],
    italianSong: false,
    date: "12/24/2020",
    title: "",
    description: "Incanto urbano.",
    songName: "Risonanza",
  },
  {
    id: 50,
    src: "/src/assets/sketches/WZWW7237.JPG",
    artist: ["rose-villain"],
    italianSong: false,
    date: "03/05/2023",
    title: "",
    description: "Eco visivo.",
    songName: "Sinfonia",
  },
].sort((a, b) => new Date(b.date) - new Date(a.date));

export default allArtPieces;
