"use strict";

/* Navbar */
const inspirationsItemBtn = document.querySelector(".inspirations_item");
console.log(inspirationsItemBtn);
const menuInspirationsEl = document.querySelector(".menu_inspirations");
console.log(menuInspirationsEl);
const collaborationsItemBtn = document.querySelector(".collaborations_item");
console.log(inspirationsItemBtn);
const menuCollaborations = document.querySelector(".menu_collaborations");
console.log(menuCollaborations);

// Functions

// Variabile per gestire il timer
let hideTimer;

// Funzione per mostrare il menu
const showMenu = function (menu) {
  clearTimeout(hideTimer);
  menu.classList.remove("u-hide");
};

// Funzione che verifica se il mouse esce sia dal link che dal menu e nasconde il menu dopo un breve ritardo
function hideMenu(link, menu) {
  hideTimer = setTimeout(() => {
    if (!link.matches(":hover") && !menu.matches(":hover")) {
      menu.classList.add("u-hide");
    }
  }, 10);
}

// Event listner
// --- Gestione per il menu Inspirations ---
inspirationsItemBtn.addEventListener("mouseenter", () =>
  showMenu(menuInspirationsEl)
);
inspirationsItemBtn.addEventListener("mouseleave", () =>
  hideMenu(inspirationsItemBtn, menuInspirationsEl)
);

menuInspirationsEl.addEventListener("mouseenter", () =>
  showMenu(menuInspirationsEl)
);
menuInspirationsEl.addEventListener("mouseleave", () =>
  hideMenu(inspirationsItemBtn, menuInspirationsEl)
);

// --- Gestione per il menu Collaborations ---
collaborationsItemBtn.addEventListener("mouseenter", () =>
  showMenu(menuCollaborations)
);
collaborationsItemBtn.addEventListener("mouseleave", () =>
  hideMenu(collaborationsItemBtn, menuCollaborations)
);

menuCollaborations.addEventListener("mouseenter", () =>
  showMenu(menuCollaborations)
);
menuCollaborations.addEventListener("mouseleave", () =>
  hideMenu(collaborationsItemBtn, menuCollaborations)
);

////////////////////////////////////////////////////////////////////////////
/* gallery */

const artPieces = [
  {
    id: 1,
    src: "./Media/sketches/APLA1458.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 2,
    src: "./Media/sketches/AQRO3052.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 3,
    src: "./Media/sketches/BAYP0451.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 4,
    src: "./Media/sketches/BHXP3462.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 5,
    src: "./Media/sketches/BNQX3333.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 6,
    src: "./Media/sketches/BPZD1936.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 7,
    src: "./Media/sketches/CITE1837.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 8,
    src: "./Media/sketches/CJLC3545.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 9,
    src: "./Media/sketches/CRFC1818.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 10,
    src: "./Media/sketches/DOUI6761.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 11,
    src: "./Media/sketches/DSNX9207.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 12,
    src: "./Media/sketches/EQYP1424.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 13,
    src: "./Media/sketches/ERQO3358.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 14,
    src: "./Media/sketches/FBFH4847.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 15,
    src: "./Media/sketches/FKNS0648.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 16,
    src: "./Media/sketches/FKVK5005.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 17,
    src: "./Media/sketches/FXLR0871.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 18,
    src: "./Media/sketches/GNQY6124.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 19,
    src: "./Media/sketches/HCAN0173.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 20,
    src: "./Media/sketches/HOOW6277.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 21,
    src: "./Media/sketches/IAHA1176.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 22,
    src: "./Media/sketches/IGCS9328.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 23,
    src: "./Media/sketches/IINJ0685.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 24,
    src: "./Media/sketches/KHAJ9471.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 25,
    src: "./Media/sketches/Kid Yugi and featurings of I Diavoli Del Male album.png",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 26,
    src: "./Media/sketches/LTWV1703.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 27,
    src: "./Media/sketches/MOPN1114.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 28,
    src: "./Media/sketches/NEJC5049.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 29,
    src: "./Media/sketches/NIKE8692.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 30,
    src: "./Media/sketches/NIOA5886.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 31,
    src: "./Media/sketches/OCHB6729.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 32,
    src: "./Media/sketches/OQMQ0348.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 33,
    src: "./Media/sketches/OQUS1839.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 34,
    src: "./Media/sketches/OWEW7931.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 35,
    src: "./Media/sketches/PIKA5237.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 36,
    src: "./Media/sketches/PIRC3235.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 37,
    src: "./Media/sketches/PVIR4809.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 38,
    src: "./Media/sketches/QDIW5520.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 39,
    src: "./Media/sketches/QFVH1418.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 40,
    src: "./Media/sketches/QUTJ4744.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 41,
    src: "./Media/sketches/QWFJ0522.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 42,
    src: "./Media/sketches/RGFU5150.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 43,
    src: "./Media/sketches/RVRD7544.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 44,
    src: "./Media/sketches/SBBS9788.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 45,
    src: "./Media/sketches/SGHY1311.MP4",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 46,
    src: "./Media/sketches/SOJJ0828.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 47,
    src: "./Media/sketches/SVIG8580.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 48,
    src: "./Media/sketches/tha-supreme-sulla-luna.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 49,
    src: "./Media/sketches/TWDW9166.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 50,
    src: "./Media/sketches/UJXX4601.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 51,
    src: "./Media/sketches/VCFR6377.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 52,
    src: "./Media/sketches/VDIE1058.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 53,
    src: "./Media/sketches/VSBF5190.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 54,
    src: "./Media/sketches/VYEO1257.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 55,
    src: "./Media/sketches/WAKW3698.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 56,
    src: "./Media/sketches/WCTL0854.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
  {
    id: 57,
    src: "./Media/sketches/WZWW7237.JPG",
    artist: [],
    italianSong: false,
    date: "",
    title: "",
    description: "",
    songName: "",
  },
];
